packages:
  # - 'packages/*'
  - 'libs/*'
  - 'libs/dynamic/*'
  # - 'apps/*'
  # - 'servers/*'
  # - 'plugins/*'
  # - 'website'
  # exclude packages that are inside test directories
  - "!**/test/**"
